export const CIUDADES_URUGUAY = [
  "Montevideo",
  "Las Piedras",
  "La Paz",
  "Pando",
  "Ciudad de la Costa",
  "Barros Blancos",
  "Toledo",
  "Santa Lucia",
  "Canelones",
  "Maldonado",
  "Punta del Este",
  "San Carlos",
  "Pan de Azucar",
  "Piriapolis",
  "Aigua",
  "Rocha",
  "Chuy",
  "Castillos",
  "La Paloma",
  "Lascano",
  "Velazquez",
  "Salto",
  "Bella Union",
  "Constitucion",
  "San Antonio",
  "Paysandu",
  "Quebracho",
  "Porvenir",
  "Mercedes",
  "Dolores",
  "Cardona",
  "Palmitas",
  "Guichon",
  "Tacuarembo",
  "Paso de los Toros",
  "San Gregorio de Polanco",
  "Ansina",
  "Rivera",
  "Tranqueras",
  "Vichadero",
  "Minas de Corrales",
  "Melo",
  "Rio Branco",
  "Fraile Muerto",
  "Tupambae",
  "Artigas",
  "Tomas Gomensoro",
  "Baltasar Brum",
  "Durazno",
  "Sarandi del Yi",
  "Carmen",
  "Blanquillo",
  "Florida",
  "Sarandi Grande",
  "Fray Marcos",
  "Casupa",
  "San Jose de Mayo",
  "Ciudad del Plata",
  "Libertad",
  "Ecilda Paullier",
  "Rodriguez",
  "Young",
  "Fray Bentos",
  "Nueva Palmira",
  "Colonia del Sacramento",
  "Rosario",
  "Juan Lacaze",
  "Carmelo",
  "Ombues de Lavalle",
  "Nueva Helvecia",
  "Colonia Suiza",
  "Trinidad",
  "Ismael Cortinas",
  "Minas",
  "Jose Pedro Varela",
  "Mariscala",
  "Solis de Mataojo",
  "Treinta y Tres",
  "Vergara",
  "Santa Clara de Olimar",
  "Rincon",
  "Tarariras",
  "Sauce",
  "Santa Rosa",
  "Progreso",
  "Atenas",
  "Cebollati",
  "Banado de Medina",
]
